added check for ability to log into server being logging in to during deploy and init remote

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -7,6 +7,12 @@ app_name=`basename $root_dir`
 
 server=${1:-cromulence}
 
+if ! ssh $server 'whoami'; then
+  echo "Cannot log into server named $server. Ensure it is properly configured in ~/.ssh/config."
+  echo "See README.md for details"
+  exit 1
+fi
+
 if [[ ! -n $(git status --porcelain) ]]; then
   echo "Deploying to $server"
   git push $server:git/$app_name.git master
